version: "3.3"

services:
  svn:
    image: haoxian/svn-server:latest
    container_name: ${CONTAINER_NAME}
    ports:
      - "80:80"
      - "3690:3690"
    volumes:
      - svn_repo:/home/svn
      - svn_config:/etc/subversion
      - svnadmin_config:/opt/svnadmin/data
      - /etc/localtime:/etc/localtime:ro
    restart: always

volumes:
  svn_repo:
    name: ${CONTAINER_NAME}-svn_repo

  svn_config:
    name: ${CONTAINER_NAME}-svn_config

  svnadmin_config:
    name: ${CONTAINER_NAME}-svnadmin_config
